version: '3'
services:
  java-maven:
    image: abanobmorkos10/java-maven:1.1.11-8
    ports:
      - 8080:8080
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
